### ISSUE TITLE
Depends on openssl which is now deprecated/insecure

### ISSUE THREAD

**Issue by seflless** [fjolnir/HTTPKit#10]
Hey there,

Was checking out your project as a small http basic file server is exactly what I was looking for. Looks like it still uses openssl, every package manager and Xcode itself are really discouraging using it because of Heartbleed. I'm going to move onto other projects, but just wanted to see if you had a quick solution to drop support for it, maybe a drop in replacement.

![screen shot 2017-04-09 at 10 41 59 am](https://cloud.githubusercontent.com/assets/1845/24838196/3e072c90-1d11-11e7-9f0c-905ec9660f91.png)

**Comment by fjolnir** [comment]
If you just use the latest version of OpenSSL, heartbleed is not an issue.
