### ISSUE TITLE
ssl dependencies

### ISSUE THREAD

**Issue by ddaddy** [fjolnir/HTTPKit#8]
Hi,
I am trying to build this using `make` however I keep getting the error `dependencies/mongoose/mongoose.c:60:10: fatal error: 'openssl/ssl.h' file not
      found
#include <openssl/ssl.h>`

I have downloaded the ssl dependency and built the framework, and tried adding both the `openssl.framework` file and libs and headers into the `iphone-openssl` folder, but still get that error.

Any pointers what i'm doing wrong?

Thanks

**Comment by fjolnir** [comment]
did you make sure all submodules are up to date(`git submodule update --init`)?

That should bring in all dependencies

**Comment by ddaddy** [comment]
Ok, i'm a bit of a noob when it comes to git. I originally just downloaded the zip, the downloaded each dependency git as zips and built them separately.

Now i've checked out this project in Xcode then ran the git command `git submodule update --init` and it seemed to download the dependencies however the Xcode project still shows the crypto and ssl files in red as not found.
Opening the SSL-for-iOS project also has missing frameworks (crypto and ssl).

Is it not possible to download an already made armv7 & arm64 dylib of this project?
I'd really appreciate it if I could grab one from you.

**Comment by fjolnir** [comment]
If you download the zip, you are not using git. Try cloning the repo with `git clone --recursive https://github.com/fjolnir/HTTPKit.git`

There is no ready made binary for this project.

**Comment by ddaddy** [comment]
I did try checking out the git and also cloning it.
I managed to get the iPhone ssl project to build eventually after having to change the sdk to 9.1 in the build file, but HTTPKit still complained of missing `libcrypto.dylib` & `libssl.dylib` file.
I found the files `libcrypto.1.0.0.dylib` & `libssl.1.0.0.dylib` on my system so linked to them.

Now the project has lots of errors in `main.m` saying `Receiver type 'HTTPConnection' for instance message is a forward declaration`

**Comment by fjolnir** [comment]
You need to execute `build-libssl.sh` inside `dependencies/iphone-openssl`.

As for the `main.m` errors; it seems I broke it when I changed `HTTPServer.h` at some point. I've fixed the repo, so pulling the latest changes will fix that for you.

**Comment by kaspesla** [comment]
I think you probably list those steps on the README! ;)

**Comment by kaspesla** [comment]
Here are the steps in case anyone else is trying use HTTPKit:
1) git clone --recursive https://github.com/fjolnir/HTTPKit.git
2) git submodule update --init
3) cd dependencies/iphone-openssl
4) Edit the SDK_VERSION build-libssl.sh to match your current Xcode's SDK version
5) ./build-libssl.sh

**Comment by fjolnir** [comment]
Thanks @kaspesla. I've updated the readme: https://github.com/fjolnir/HTTPKit/commit/e92acd7004466ff0d38cd620cc0453a5324dc0de
